import type {
  CommandAudienceDefinition,
  CommandAuthRequirementDefinition,
  CommandHostDependencyDefinition,
  CommandHostProfileIdDefinition,
  CommandHostSupportTierDefinition,
  CommandMutabilityDefinition,
  CommandSafetyTierDefinition,
} from "./command-surface-definition-types";
import {
  listCommandHostAccessOverrideIds,
  resolveLegacyCommandHostDependencies,
  resolveLegacyCommandHostProfiles,
  resolveLegacyCommandHostSupportTier,
} from "../host/command-host-metadata";

// Keep the tables data-only so command-surface-definitions.ts remains the only
// place that defines fallback defaults and resolution semantics.
export const COMMAND_AUDIENCE_OVERRIDES = {
  "app.accounts": "operator",
  "app.login": "operator",
  "app.shared_open": "operator",
  "app.shared_start": "operator",
  "app.shared_status": "operator",
  "app.shared_watchdog": "operator",
  "app.start": "operator",
  "background.install": "operator",
  "background.uninstall": "operator",
  "operator.hermes.install_skill": "operator",
  "operator.hermes.smoke": "operator",
  "operator.hermes.status": "operator",
  "operator.hermes.sync_checkin": "operator",
  "operator.help": "operator",
  "operator.schema": "operator",
  "system.checkin_poller": "operator",
} as const satisfies Record<string, CommandAudienceDefinition>;

export const COMMAND_SAFETY_OVERRIDES = {
  "app.accounts": "operator",
  "app.doctor": "open",
  "app.help": "open",
  "app.login": "operator",
  "app.schema": "open",
  "app.shared_open": "operator",
  "app.shared_start": "operator",
  "app.shared_status": "operator",
  "app.shared_watchdog": "operator",
  "app.start": "operator",
  "background.install": "operator",
  "background.uninstall": "operator",
  "channel.send_file": "warned",
  "companion.remember": "warned",
  "diary.append": "warned",
  "host.bootstrap": "warned",
  "host.claim_checkin": "warned",
  "host.seed_proactive": "warned",
  "host.settle_checkin": "warned",
  "onboarding.reset": "warned",
  "onboarding.start": "warned",
  "onboarding.status": "open",
  "onboarding.step": "warned",
  "note.auto": "warned",
  "note.maybe": "open",
  "note.sync": "warned",
  "operator.hermes.install_skill": "operator",
  "operator.hermes.smoke": "operator",
  "operator.hermes.status": "operator",
  "operator.hermes.sync_checkin": "operator",
  "operator.help": "operator",
  "operator.schema": "operator",
  "project.radar": "open",
  "reminder.create": "warned",
  "review.monthly": "warned",
  "review.nightly": "warned",
  "review.weekly": "warned",
  "system.checkin_config": "warned",
  "system.checkin_complete": "warned",
  "system.checkin_tick": "warned",
  "system.checkin_trigger": "open",
  "system.checkin_poller": "operator",
  "system.send": "warned",
  "timeline.build": "open",
  "timeline.categories": "open",
  "timeline.dev": "open",
  "timeline.event": "warned",
  "timeline.proposals": "open",
  "timeline.read": "open",
  "timeline.screenshot": "warned",
  "timeline.serve": "open",
  "timeline.write": "warned",
} as const satisfies Record<string, CommandSafetyTierDefinition>;

export const COMMAND_MUTABILITY_OVERRIDES = {
  "app.accounts": "bootstrap",
  "app.doctor": "read",
  "app.help": "read",
  "app.login": "bootstrap",
  "app.schema": "read",
  "app.shared_open": "bootstrap",
  "app.shared_start": "long_running",
  "app.shared_status": "read",
  "app.shared_watchdog": "long_running",
  "app.start": "long_running",
  "background.install": "bootstrap",
  "background.uninstall": "bootstrap",
  "channel.send_file": "write",
  "companion.remember": "write",
  "diary.append": "write",
  "host.bootstrap": "bootstrap",
  "host.claim_checkin": "write",
  "host.doctor": "read",
  "host.manifest": "read",
  "host.render": "read",
  "host.seed_proactive": "write",
  "host.settle_checkin": "write",
  "host.smoke": "read",
  "onboarding.reset": "write",
  "onboarding.start": "write",
  "onboarding.status": "read",
  "onboarding.step": "write",
  "note.auto": "write",
  "note.maybe": "read",
  "note.sync": "write",
  "operator.hermes.install_skill": "write",
  "operator.hermes.smoke": "read",
  "operator.hermes.status": "read",
  "operator.hermes.sync_checkin": "write",
  "operator.help": "read",
  "operator.schema": "read",
  "project.radar": "read",
  "reminder.create": "write",
  "review.monthly": "write",
  "review.nightly": "write",
  "review.weekly": "write",
  "system.checkin_config": "write",
  "system.checkin_complete": "write",
  "system.checkin_tick": "write",
  "system.checkin_trigger": "read",
  "system.checkin_poller": "long_running",
  "system.send": "write",
  "timeline.build": "read",
  "timeline.categories": "read",
  "timeline.dev": "long_running",
  "timeline.event": "write",
  "timeline.proposals": "read",
  "timeline.read": "read",
  "timeline.screenshot": "write",
  "timeline.serve": "long_running",
  "timeline.write": "write",
} as const satisfies Record<string, CommandMutabilityDefinition>;

export const COMMAND_AUTH_OVERRIDES = {
  "app.accounts": "weixin_account",
  "app.login": "none",
  "app.shared_open": "runtime_bootstrap",
  "app.shared_start": "runtime_bootstrap",
  "app.shared_status": "runtime_bootstrap",
  "app.shared_watchdog": "runtime_bootstrap",
  "app.start": "runtime_bootstrap",
  "channel.send_file": "runtime_bootstrap",
  "reminder.create": "context_token",
  "system.send": "context_token",
  // `timeline screenshot` without `--send` is host-neutral, but the same
  // public action also retains the compatibility `--send` wrapper. Because the
  // static command surface cannot express option-sensitive auth today, keep
  // the action-level contract conservative instead of promising auth-free send
  // flows to hosts that only inspect manifest metadata.
  "timeline.screenshot": "context_token",
} as const satisfies Record<string, CommandAuthRequirementDefinition>;

export const COMMAND_HOST_SUPPORT_TIER_OVERRIDES = Object.freeze(
  Object.fromEntries(
    listCommandHostAccessOverrideIds().map((actionId) => [actionId, resolveLegacyCommandHostSupportTier(actionId)]),
  ),
) as Readonly<Record<string, CommandHostSupportTierDefinition>>;

export const COMMAND_HOST_DEPENDENCY_OVERRIDES = Object.freeze(
  Object.fromEntries(
    listCommandHostAccessOverrideIds().map((actionId) => [actionId, resolveLegacyCommandHostDependencies(actionId)]),
  ),
) as Readonly<Record<string, readonly CommandHostDependencyDefinition[]>>;

export const COMMAND_HOST_PROFILE_OVERRIDES = Object.freeze(
  Object.fromEntries(
    listCommandHostAccessOverrideIds().map((actionId) => [actionId, resolveLegacyCommandHostProfiles(actionId)]),
  ),
) as Readonly<Record<string, readonly CommandHostProfileIdDefinition[]>>;
