import type {
  CommandAudienceDefinition,
  CommandAuthRequirementDefinition,
  CommandHostDependencyDefinition,
  CommandHostProfileIdDefinition,
  CommandHostSupportTierDefinition,
  CommandMutabilityDefinition,
  CommandSafetyTierDefinition,
} from "./command-surface-definition-types";

// Keep the tables data-only so command-surface-definitions.ts remains the only
// place that defines fallback defaults and resolution semantics.
export const COMMAND_AUDIENCE_OVERRIDES = {
  "app.accounts": "operator",
  "app.login": "operator",
  "app.shared_open": "operator",
  "app.shared_start": "operator",
  "app.shared_status": "operator",
  "app.shared_watchdog": "operator",
  "app.start": "operator",
  "background.install": "operator",
  "background.uninstall": "operator",
  "operator.hermes.install_skill": "operator",
  "operator.hermes.smoke": "operator",
  "operator.hermes.status": "operator",
  "operator.hermes.sync_checkin": "operator",
  "operator.help": "operator",
  "operator.schema": "operator",
  "system.checkin_poller": "operator",
} as const satisfies Record<string, CommandAudienceDefinition>;

export const COMMAND_SAFETY_OVERRIDES = {
  "app.accounts": "operator",
  "app.doctor": "open",
  "app.help": "open",
  "app.login": "operator",
  "app.schema": "open",
  "app.shared_open": "operator",
  "app.shared_start": "operator",
  "app.shared_status": "operator",
  "app.shared_watchdog": "operator",
  "app.start": "operator",
  "background.install": "operator",
  "background.uninstall": "operator",
  "channel.send_file": "warned",
  "diary.append": "warned",
  "note.auto": "warned",
  "note.maybe": "open",
  "note.sync": "warned",
  "operator.hermes.install_skill": "operator",
  "operator.hermes.smoke": "operator",
  "operator.hermes.status": "operator",
  "operator.hermes.sync_checkin": "operator",
  "operator.help": "operator",
  "operator.schema": "operator",
  "project.radar": "open",
  "reminder.create": "warned",
  "review.monthly": "warned",
  "review.nightly": "warned",
  "review.weekly": "warned",
  "system.checkin_config": "warned",
  "system.checkin_complete": "warned",
  "system.checkin_tick": "warned",
  "system.checkin_trigger": "open",
  "system.checkin_poller": "operator",
  "system.send": "warned",
  "timeline.build": "open",
  "timeline.categories": "open",
  "timeline.dev": "open",
  "timeline.event": "warned",
  "timeline.proposals": "open",
  "timeline.read": "open",
  "timeline.screenshot": "warned",
  "timeline.serve": "open",
  "timeline.write": "warned",
} as const satisfies Record<string, CommandSafetyTierDefinition>;

export const COMMAND_MUTABILITY_OVERRIDES = {
  "app.accounts": "bootstrap",
  "app.doctor": "read",
  "app.help": "read",
  "app.login": "bootstrap",
  "app.schema": "read",
  "app.shared_open": "bootstrap",
  "app.shared_start": "long_running",
  "app.shared_status": "read",
  "app.shared_watchdog": "long_running",
  "app.start": "long_running",
  "background.install": "bootstrap",
  "background.uninstall": "bootstrap",
  "channel.send_file": "write",
  "diary.append": "write",
  "note.auto": "write",
  "note.maybe": "read",
  "note.sync": "write",
  "operator.hermes.install_skill": "write",
  "operator.hermes.smoke": "read",
  "operator.hermes.status": "read",
  "operator.hermes.sync_checkin": "write",
  "operator.help": "read",
  "operator.schema": "read",
  "project.radar": "read",
  "reminder.create": "write",
  "review.monthly": "write",
  "review.nightly": "write",
  "review.weekly": "write",
  "system.checkin_config": "write",
  "system.checkin_complete": "write",
  "system.checkin_tick": "write",
  "system.checkin_trigger": "read",
  "system.checkin_poller": "long_running",
  "system.send": "write",
  "timeline.build": "read",
  "timeline.categories": "read",
  "timeline.dev": "long_running",
  "timeline.event": "write",
  "timeline.proposals": "read",
  "timeline.read": "read",
  "timeline.screenshot": "write",
  "timeline.serve": "long_running",
  "timeline.write": "write",
} as const satisfies Record<string, CommandMutabilityDefinition>;

export const COMMAND_AUTH_OVERRIDES = {
  "app.accounts": "weixin_account",
  "app.login": "none",
  "app.shared_open": "runtime_bootstrap",
  "app.shared_start": "runtime_bootstrap",
  "app.shared_status": "runtime_bootstrap",
  "app.shared_watchdog": "runtime_bootstrap",
  "app.start": "runtime_bootstrap",
  "channel.send_file": "runtime_bootstrap",
  "reminder.create": "context_token",
  "system.send": "context_token",
  "timeline.screenshot": "context_token",
} as const satisfies Record<string, CommandAuthRequirementDefinition>;

export const COMMAND_HOST_SUPPORT_TIER_OVERRIDES = {
  "app.accounts": "bridge_only",
  "app.doctor": "hosted_ready",
  "app.login": "bridge_only",
  "app.shared_open": "bridge_only",
  "app.shared_start": "bridge_only",
  "app.shared_status": "bridge_only",
  "app.shared_watchdog": "bridge_only",
  "app.start": "bridge_only",
  "background.install": "bridge_only",
  "background.uninstall": "bridge_only",
  "channel.send_file": "hosted_ready",
  "diary.append": "host_neutral",
  "note.auto": "host_neutral",
  "note.maybe": "host_neutral",
  "note.sync": "host_neutral",
  "operator.hermes.install_skill": "hosted_ready",
  "operator.hermes.smoke": "hosted_ready",
  "operator.hermes.status": "hosted_ready",
  "operator.hermes.sync_checkin": "hosted_ready",
  "project.radar": "host_neutral",
  "reminder.create": "hosted_ready",
  "review.monthly": "host_neutral",
  "review.nightly": "host_neutral",
  "review.weekly": "host_neutral",
  "system.checkin_complete": "host_neutral",
  "system.checkin_poller": "bridge_only",
  "system.checkin_tick": "host_neutral",
  "system.checkin_trigger": "host_neutral",
  "system.send": "bridge_state_dependent",
  "timeline.build": "host_neutral",
  "timeline.categories": "host_neutral",
  "timeline.dev": "host_neutral",
  "timeline.event": "host_neutral",
  "timeline.proposals": "host_neutral",
  "timeline.read": "host_neutral",
  "timeline.screenshot": "hosted_ready",
  "timeline.serve": "host_neutral",
  "timeline.write": "host_neutral",
} as const satisfies Record<string, CommandHostSupportTierDefinition>;

export const COMMAND_HOST_DEPENDENCY_OVERRIDES = {
  "app.accounts": ["weixin_account"] as const,
  "app.login": ["weixin_account"] as const,
  "app.shared_open": ["bridge_runtime"] as const,
  "app.shared_start": ["bridge_runtime"] as const,
  "app.shared_status": ["bridge_runtime"] as const,
  "app.shared_watchdog": ["bridge_runtime"] as const,
  "app.start": ["bridge_runtime"] as const,
  "background.install": ["bridge_runtime"] as const,
  "background.uninstall": ["bridge_runtime"] as const,
  "channel.send_file": ["bridge_file_delivery", "hosted_repo_local_delivery", "hosted_session_lookup"] as const,
  "operator.hermes.install_skill": ["hosted_companion_skill"] as const,
  "operator.hermes.smoke": ["hosted_companion_skill"] as const,
  "operator.hermes.status": ["hosted_companion_skill"] as const,
  "operator.hermes.sync_checkin": ["hosted_companion_skill", "hosted_repo_local_cron", "hosted_session_lookup"] as const,
  "reminder.create": ["bridge_queue", "context_token", "weixin_account", "hosted_repo_local_cron", "hosted_session_lookup"] as const,
  "system.checkin_poller": ["bridge_queue", "bridge_runtime", "weixin_account"] as const,
  "system.send": ["bridge_queue", "context_token", "weixin_account"] as const,
  "timeline.screenshot": ["bridge_file_delivery", "bridge_queue", "context_token", "hosted_repo_local_delivery", "hosted_session_lookup"] as const,
} as const satisfies Record<string, readonly CommandHostDependencyDefinition[]>;

export const COMMAND_HOST_PROFILE_OVERRIDES = {
  "app.accounts": ["bridge-codex-weixin"] as const,
  "app.login": ["bridge-codex-weixin"] as const,
  "app.shared_open": ["bridge-codex-weixin"] as const,
  "app.shared_start": ["bridge-codex-weixin"] as const,
  "app.shared_status": ["bridge-codex-weixin"] as const,
  "app.shared_watchdog": ["bridge-codex-weixin"] as const,
  "app.start": ["bridge-codex-weixin"] as const,
  "background.install": ["bridge-codex-weixin"] as const,
  "background.uninstall": ["bridge-codex-weixin"] as const,
  "channel.send_file": ["bridge-codex-weixin", "hosted-hermes-weixin"] as const,
  "operator.hermes.sync_checkin": ["hosted-hermes-weixin"] as const,
  "reminder.create": ["bridge-codex-weixin", "hosted-hermes-weixin"] as const,
  "system.checkin_poller": ["bridge-codex-weixin"] as const,
  "system.send": ["bridge-codex-weixin"] as const,
  "timeline.screenshot": ["bridge-codex-weixin", "hosted-hermes-weixin"] as const,
} as const satisfies Record<string, readonly CommandHostProfileIdDefinition[]>;
