import type { CommandActionDefinition } from "./command-surface-definition-types";

export const LIFECYCLE_COMMAND_ACTION_DEFINITIONS = [
  {
    action: "host.manifest",
    groupId: "lifecycle",
    summary: "输出 host attachment manifest / hostkit 机器入口",
    terminal: ["host manifest"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "manifest",
    runner: "host.manifest",
    argsSchemaKey: "hostManifest",
    help: { topic: "host", leafKey: "host.manifest", detail: "leaf" },
  },
  {
    action: "host.bootstrap",
    groupId: "lifecycle",
    summary: "写入 canonical host config，并按 provider 做最小 bootstrap",
    terminal: ["host bootstrap"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "bootstrap",
    runner: "host.bootstrap",
    argsSchemaKey: "hostBootstrap",
    help: { topic: "host", leafKey: "host.bootstrap", detail: "leaf" },
    sideEffects: [
      {
        kind: "write_canonical_config",
        target: "codeksei.config.json",
      },
      {
        kind: "bootstrap_provider_recipe",
        target: "provider-specific",
        when: "provider 支持 install/doctor/bootstrap side effects 时",
      },
    ],
  },
  {
    action: "host.doctor",
    groupId: "lifecycle",
    summary: "统一查看 daemon / attachment / provider recipe 状态",
    terminal: ["host doctor"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "doctor",
    runner: "host.doctor",
    argsSchemaKey: "hostDoctor",
    help: { topic: "host", leafKey: "host.doctor", detail: "leaf" },
  },
  {
    action: "host.smoke",
    groupId: "lifecycle",
    summary: "执行 provider recipe 的最小 attach smoke",
    terminal: ["host smoke"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "smoke",
    runner: "host.smoke",
    argsSchemaKey: "hostSmoke",
    help: { topic: "host", leafKey: "host.smoke", detail: "leaf" },
  },
  {
    action: "host.seed_proactive",
    groupId: "lifecycle",
    summary: "为 delegated proactive checkin 种下或修复第一条 future wake",
    terminal: ["host seed-proactive"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "seed-proactive",
    runner: "host.seed_proactive",
    argsSchemaKey: "hostSeedProactive",
    help: { topic: "host", leafKey: "host.seed_proactive", detail: "leaf" },
    sideEffects: [
      {
        kind: "seed_proactive_wake",
        target: "checkin schedule state / hosted wake job",
      },
    ],
  },
  {
    action: "host.claim_checkin",
    groupId: "lifecycle",
    summary: "原子 claim 一次 proactive checkin 执行 lease",
    terminal: ["host claim-checkin"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "claim-checkin",
    runner: "host.claim_checkin",
    argsSchemaKey: "hostClaimCheckin",
    help: { topic: "host", leafKey: "host.claim_checkin", detail: "leaf" },
    sideEffects: [
      {
        kind: "claim_delegated_checkin_lease",
        target: "checkin schedule state / hosted recovery wake",
      },
    ],
  },
  {
    action: "host.settle_checkin",
    groupId: "lifecycle",
    summary: "回写 delegated proactive checkin 的完成结果",
    terminal: ["host settle-checkin"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "settle-checkin",
    runner: "host.settle_checkin",
    argsSchemaKey: "hostSettleCheckin",
    help: { topic: "host", leafKey: "host.settle_checkin", detail: "leaf" },
    sideEffects: [
      {
        kind: "settle_delegated_checkin_lease",
        target: "checkin schedule state / hosted wake job",
      },
    ],
  },
  {
    action: "host.finalize_checkin",
    groupId: "lifecycle",
    summary: "由主会话消费 pending handoff 并 finalize proactive checkin",
    terminal: ["host finalize-checkin"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "finalize-checkin",
    runner: "host.finalize_checkin",
    argsSchemaKey: "hostFinalizeCheckin",
    help: { topic: "host", leafKey: "host.finalize_checkin", detail: "leaf" },
    sideEffects: [
      {
        kind: "finalize_delegated_checkin_handoff",
        target: "checkin schedule state / hosted wake job",
      },
    ],
  },
  {
    action: "host.render",
    groupId: "lifecycle",
    summary: "从 command truth 渲染 provider-facing host asset",
    terminal: ["host render"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "host",
    subcommand: "render",
    runner: "host.render",
    argsSchemaKey: "hostRender",
    help: { topic: "host", leafKey: "host.render", detail: "leaf" },
  },
  {
    action: "operator.hermes.install_skill",
    groupId: "lifecycle",
    summary: "同步仓内 Codeksei companion skill 到当前 Hermes home",
    terminal: ["operator hermes install-skill"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "operator",
    subcommand: "hermes install-skill",
    runner: "operator.hermes.install_skill",
    argsSchemaKey: "hermesInstallSkill",
    help: { topic: "", leafKey: "operator.hermes.install_skill", detail: "leaf" },
    sideEffects: [
      {
        kind: "write_skill_file",
        target: "~/.hermes/skills/codeksei-companion/SKILL.md",
        when: "当目标不存在或内容与仓内 skill asset 不一致时",
      },
      {
        kind: "backup_existing_skill",
        target: "~/.hermes/skills/codeksei-companion/SKILL.md.backup-<timestamp>",
        when: "当已安装 skill 存在且将被覆盖时",
      },
    ],
  },
  {
    action: "operator.hermes.status",
    groupId: "lifecycle",
    summary: "查看 Hermes hosted 集成状态、skill 同步与 semantic review 可用性",
    terminal: ["operator hermes status"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "operator",
    subcommand: "hermes status",
    runner: "operator.hermes.status",
    argsSchemaKey: "hermesStatus",
    help: { topic: "", leafKey: "operator.hermes.status", detail: "leaf" },
  },
  {
    action: "operator.hermes.smoke",
    groupId: "lifecycle",
    summary: "执行 Hermes hosted 前置检查与 skill parity smoke",
    terminal: ["operator hermes smoke"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "operator",
    subcommand: "hermes smoke",
    runner: "operator.hermes.smoke",
    argsSchemaKey: "hermesSmoke",
    help: { topic: "", leafKey: "operator.hermes.smoke", detail: "leaf" },
  },
  {
    action: "app.login",
    groupId: "lifecycle",
    summary: "发起 Codeksei 自带微信桥的扫码登录并保存账号（bridge-only）",
    terminal: ["login"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "login",
    command: "login",
    runner: "login",
    argsSchemaKey: "appLogin",
    help: { topic: "", leafKey: "app.login", detail: "topic_only" },
  },
  {
    action: "app.accounts",
    groupId: "lifecycle",
    summary: "查看 Codeksei 自带微信桥的本地已保存账号（bridge-only）",
    terminal: ["accounts"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "accounts",
    command: "accounts",
    runner: "accounts",
    argsSchemaKey: "appAccounts",
    help: { topic: "", leafKey: "app.accounts", detail: "topic_only" },
  },
  {
    action: "app.start",
    groupId: "lifecycle",
    summary: "启动当前 Codeksei bridge 主循环（bridge-only）",
    terminal: ["start"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "start",
    command: "start",
    runner: "start",
    argsSchemaKey: "appStart",
    help: { topic: "", leafKey: "app.start", detail: "topic_only" },
  },
  {
    action: "app.shared_start",
    groupId: "lifecycle",
    summary: "启动共享 app-server 与共享微信桥接（bridge-only）",
    terminal: ["shared:start"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:start",
  },
  {
    action: "app.shared_open",
    groupId: "lifecycle",
    summary: "接入当前微信绑定的共享线程（bridge-only）",
    terminal: ["shared:open"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:open",
  },
  {
    action: "app.shared_status",
    groupId: "lifecycle",
    summary: "查看共享桥接状态；Hermes hosted mode 下仅显示宿主管理提示",
    terminal: ["shared:status"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:status",
  },
  {
    action: "app.shared_watchdog",
    groupId: "lifecycle",
    summary: "主动巡检并自恢复共享链路（bridge-only）",
    terminal: ["shared:watchdog"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:watchdog",
  },
  {
    action: "background.install",
    groupId: "lifecycle",
    summary: "Windows 安装开机自启与周期巡检",
    terminal: ["background:install"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "background:install",
  },
  {
    action: "background.uninstall",
    groupId: "lifecycle",
    summary: "Windows 卸载开机自启与周期巡检",
    terminal: ["background:uninstall"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "background:uninstall",
  },
  {
    action: "app.doctor",
    groupId: "lifecycle",
    summary: "打印当前配置、边界和线程状态",
    terminal: ["doctor"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "doctor",
    command: "doctor",
    runner: "doctor",
    argsSchemaKey: "appDoctor",
    help: { topic: "system", leafKey: "app.doctor", detail: "leaf" },
  },
  {
    action: "system.checkin_config",
    groupId: "lifecycle",
    summary: "查看或修改主动 check-in 的 fallback 区间",
    terminal: ["system checkin"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "system",
    subcommand: "checkin",
    runner: "system.checkin-config",
    argsSchemaKey: "systemCheckinConfig",
    help: { topic: "system", leafKey: "system.checkin_config", detail: "leaf" },
  },
  {
    action: "system.checkin_trigger",
    groupId: "lifecycle",
    summary: "生成一次 host-neutral 的主动 check-in backstage trigger",
    terminal: ["system checkin-trigger"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:checkin-trigger",
    command: "system",
    subcommand: "checkin-trigger",
    runner: "system.checkin-trigger",
    argsSchemaKey: "systemCheckinTrigger",
    help: { topic: "system", leafKey: "system.checkin_trigger", detail: "leaf" },
  },
  {
    action: "system.checkin_tick",
    groupId: "lifecycle",
    summary: "轮询或确认 host-neutral check-in 调度状态（tick/ack）",
    terminal: ["system checkin-tick"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:checkin-tick",
    command: "system",
    subcommand: "checkin-tick",
    runner: "system.checkin-tick",
    argsSchemaKey: "systemCheckinTick",
    help: { topic: "system", leafKey: "system.checkin_tick", detail: "leaf" },
  },
  {
    action: "system.checkin_complete",
    groupId: "lifecycle",
    summary: "写回这轮 proactive check-in 的完成结果与下一次唤醒时间",
    terminal: ["system checkin-complete"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:checkin-complete",
    command: "system",
    subcommand: "checkin-complete",
    runner: "system.checkin-complete",
    argsSchemaKey: "systemCheckinComplete",
    help: { topic: "system", leafKey: "system.checkin_complete", detail: "leaf" },
  },
] as const satisfies readonly CommandActionDefinition[];
