import type { CommandActionDefinition } from "./command-surface-definition-types";

export const LIFECYCLE_COMMAND_ACTION_DEFINITIONS = [
  {
    action: "operator.hermes.install_skill",
    groupId: "lifecycle",
    summary: "同步仓内 Codeksei companion skill 到当前 Hermes home",
    terminal: ["operator hermes install-skill"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "operator",
    subcommand: "hermes install-skill",
    runner: "operator.hermes.install_skill",
    argsSchemaKey: "hermesInstallSkill",
    help: { topic: "", leafKey: "operator.hermes.install_skill", detail: "leaf" },
    sideEffects: [
      {
        kind: "write_skill_file",
        target: "~/.hermes/skills/codeksei-companion/SKILL.md",
        when: "当目标不存在或内容与仓内 skill asset 不一致时",
      },
      {
        kind: "backup_existing_skill",
        target: "~/.hermes/skills/codeksei-companion/SKILL.md.backup-<timestamp>",
        when: "当已安装 skill 存在且将被覆盖时",
      },
    ],
  },
  {
    action: "operator.hermes.status",
    groupId: "lifecycle",
    summary: "查看 Hermes hosted 集成状态、skill 同步与 semantic review 可用性",
    terminal: ["operator hermes status"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "operator",
    subcommand: "hermes status",
    runner: "operator.hermes.status",
    argsSchemaKey: "hermesStatus",
    help: { topic: "", leafKey: "operator.hermes.status", detail: "leaf" },
  },
  {
    action: "operator.hermes.smoke",
    groupId: "lifecycle",
    summary: "执行 Hermes hosted 前置检查与 skill parity smoke",
    terminal: ["operator hermes smoke"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "operator",
    subcommand: "hermes smoke",
    runner: "operator.hermes.smoke",
    argsSchemaKey: "hermesSmoke",
    help: { topic: "", leafKey: "operator.hermes.smoke", detail: "leaf" },
  },
  {
    action: "app.login",
    groupId: "lifecycle",
    summary: "发起 Codeksei 自带微信桥的扫码登录并保存账号（bridge-only）",
    terminal: ["login"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "login",
    command: "login",
    runner: "login",
  },
  {
    action: "app.accounts",
    groupId: "lifecycle",
    summary: "查看 Codeksei 自带微信桥的本地已保存账号（bridge-only）",
    terminal: ["accounts"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "accounts",
    command: "accounts",
    runner: "accounts",
  },
  {
    action: "app.start",
    groupId: "lifecycle",
    summary: "启动当前 Codeksei bridge 主循环（bridge-only）",
    terminal: ["start"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "start",
    command: "start",
    runner: "start",
  },
  {
    action: "app.shared_start",
    groupId: "lifecycle",
    summary: "启动共享 app-server 与共享微信桥接（bridge-only）",
    terminal: ["shared:start"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:start",
  },
  {
    action: "app.shared_open",
    groupId: "lifecycle",
    summary: "接入当前微信绑定的共享线程（bridge-only）",
    terminal: ["shared:open"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:open",
  },
  {
    action: "app.shared_status",
    groupId: "lifecycle",
    summary: "查看共享桥接状态；Hermes hosted mode 下仅显示宿主管理提示",
    terminal: ["shared:status"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:status",
  },
  {
    action: "app.shared_watchdog",
    groupId: "lifecycle",
    summary: "主动巡检并自恢复共享链路（bridge-only）",
    terminal: ["shared:watchdog"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "shared:watchdog",
  },
  {
    action: "background.install",
    groupId: "lifecycle",
    summary: "Windows 安装开机自启与周期巡检",
    terminal: ["background:install"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "background:install",
  },
  {
    action: "background.uninstall",
    groupId: "lifecycle",
    summary: "Windows 卸载开机自启与周期巡检",
    terminal: ["background:uninstall"],
    weixin: [],
    status: "active",
    entrypointType: "script",
    scriptName: "background:uninstall",
  },
  {
    action: "app.doctor",
    groupId: "lifecycle",
    summary: "打印当前配置、边界和线程状态",
    terminal: ["doctor"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "doctor",
    command: "doctor",
    runner: "doctor",
    help: { topic: "system", leafKey: "app.doctor", detail: "leaf" },
  },
  {
    action: "system.send",
    groupId: "lifecycle",
    summary: "向内部系统队列写入一条不可见触发消息",
    terminal: ["system send"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:send",
    command: "system",
    subcommand: "send",
    runner: "system.send",
    argsSchemaKey: "systemSend",
    help: { topic: "system", leafKey: "system.send", detail: "leaf" },
  },
  {
    action: "system.checkin_config",
    groupId: "lifecycle",
    summary: "查看或修改主动 check-in 的 fallback 区间",
    terminal: ["system checkin"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    command: "system",
    subcommand: "checkin",
    runner: "system.checkin-config",
    argsSchemaKey: "systemCheckinConfig",
    help: { topic: "system", leafKey: "system.checkin_config", detail: "leaf" },
  },
  {
    action: "system.checkin_trigger",
    groupId: "lifecycle",
    summary: "生成一次 host-neutral 的主动 check-in backstage trigger",
    terminal: ["system checkin-trigger"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:checkin-trigger",
    command: "system",
    subcommand: "checkin-trigger",
    runner: "system.checkin-trigger",
    argsSchemaKey: "systemCheckinTrigger",
    help: { topic: "system", leafKey: "system.checkin_trigger", detail: "leaf" },
  },
  {
    action: "system.checkin_tick",
    groupId: "lifecycle",
    summary: "轮询或确认 host-neutral check-in 调度状态（tick/ack）",
    terminal: ["system checkin-tick"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:checkin-tick",
    command: "system",
    subcommand: "checkin-tick",
    runner: "system.checkin-tick",
    argsSchemaKey: "systemCheckinTick",
    help: { topic: "system", leafKey: "system.checkin_tick", detail: "leaf" },
  },
  {
    action: "system.checkin_complete",
    groupId: "lifecycle",
    summary: "写回这轮 proactive check-in 的完成结果与下一次唤醒时间",
    terminal: ["system checkin-complete"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:checkin-complete",
    command: "system",
    subcommand: "checkin-complete",
    runner: "system.checkin-complete",
    argsSchemaKey: "systemCheckinComplete",
    help: { topic: "system", leafKey: "system.checkin_complete", detail: "leaf" },
  },
  {
    action: "system.checkin_poller",
    groupId: "lifecycle",
    summary: "Bridge Mode 下按 heartbeat 驱动 check-in tick 并在本地入队",
    terminal: ["system checkin-poller"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "system:checkin",
    command: "system",
    subcommand: "checkin-poller",
    runner: "system.checkin-poller",
    help: { topic: "system", leafKey: "system.checkin_poller", detail: "topic_only" },
  },
] as const satisfies readonly CommandActionDefinition[];
