import type { CommandActionDefinition } from "./command-surface-definition-types";

export const PROJECTS_COMMAND_ACTION_DEFINITIONS = [
  {
    action: "project.radar",
    groupId: "projects",
    summary: "读取已跟踪代码项目的稳定入口与轻量 git 近况",
    terminal: ["project radar"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "project:radar",
    command: "project",
    subcommand: "radar",
    runner: "project.radar",
    argsSchemaKey: "projectRadar",
    help: { topic: "project", leafKey: "project.radar", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "note.sync",
    groupId: "projects",
    summary: "把轻量 durable 摘要同步到指定 note 的指定 section",
    terminal: ["note sync"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "note:sync",
    command: "note",
    subcommand: "sync",
    runner: "note.sync",
    argsSchemaKey: "noteSync",
    help: { topic: "note", leafKey: "note.sync", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "note.auto",
    groupId: "projects",
    summary: "按 workspace durable note schema 自动选择 note 与 section 并落盘",
    terminal: ["note auto"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "note:auto",
    command: "note",
    subcommand: "auto",
    runner: "note.auto",
    argsSchemaKey: "noteAuto",
    help: { topic: "note", leafKey: "note.auto", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "note.maybe",
    groupId: "projects",
    summary: "预览 durable note 路由，不实际写入",
    terminal: ["note maybe"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "note:maybe",
    command: "note",
    subcommand: "maybe",
    runner: "note.maybe",
    argsSchemaKey: "noteAuto",
    help: { topic: "note", leafKey: "note.maybe", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "review.nightly",
    groupId: "projects",
    summary: "从日记真相源生成一份睡前收口",
    terminal: ["review nightly"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "review:nightly",
    command: "review",
    subcommand: "nightly",
    runner: "review.command",
    argsSchemaKey: "review",
    help: { topic: "review", leafKey: "review.nightly", detail: "leaf" },
    kind: "nightly",
    approval: { autoApprove: true },
  },
  {
    action: "review.weekly",
    groupId: "projects",
    summary: "从日记真相源生成一份周复盘",
    terminal: ["review weekly"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "review:weekly",
    command: "review",
    subcommand: "weekly",
    runner: "review.command",
    argsSchemaKey: "review",
    help: { topic: "review", leafKey: "review.weekly", detail: "leaf" },
    kind: "weekly",
    approval: { autoApprove: true },
  },
  {
    action: "review.monthly",
    groupId: "projects",
    summary: "从日记真相源生成一份月复盘",
    terminal: ["review monthly"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "review:monthly",
    command: "review",
    subcommand: "monthly",
    runner: "review.command",
    argsSchemaKey: "review",
    help: { topic: "review", leafKey: "review.monthly", detail: "leaf" },
    kind: "monthly",
    approval: { autoApprove: true },
  },
] as const satisfies readonly CommandActionDefinition[];
