import type { CommandActionDefinition } from "./command-surface-definition-types";

export const CAPABILITIES_COMMAND_ACTION_DEFINITIONS = [
  {
    action: "capabilities.status",
    groupId: "capabilities",
    summary: "解释当前能力配置、可用性和不可用原因",
    terminal: ["capabilities status"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "capabilities:status",
    command: "capabilities",
    subcommand: "status",
    runner: "capabilities.status",
    argsSchemaKey: "capabilitiesStatus",
    help: { topic: "capabilities", leafKey: "capabilities.status", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "model.inspect",
    groupId: "capabilities",
    summary: "查看当前模型与 effort",
    terminal: [],
    weixin: ["/model"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "model.select",
    groupId: "capabilities",
    summary: "切换到指定模型，可选同时设置 effort",
    terminal: [],
    weixin: ["/model <id> [effort]"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "effort.inspect",
    groupId: "capabilities",
    summary: "查看当前 effort",
    terminal: [],
    weixin: ["/effort"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "effort.select",
    groupId: "capabilities",
    summary: "只调整当前 effort",
    terminal: [],
    weixin: ["/effort <level>"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "checkin.inspect",
    groupId: "capabilities",
    summary: "查看当前 checkin 区间",
    terminal: [],
    weixin: ["/checkin"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "checkin.select",
    groupId: "capabilities",
    summary: "修改或重置 checkin 区间",
    terminal: [],
    weixin: ["/checkin <min>-<max>", "/checkin reset"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "reply.inspect",
    groupId: "capabilities",
    summary: "查看当前微信回复投递模式与分片合并阈值",
    terminal: [],
    weixin: ["/reply"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "reply.configure",
    groupId: "capabilities",
    summary: "调整微信回复投递模式或短片段合并阈值",
    terminal: [],
    weixin: ["/reply mode stream|settled", "/reply merge <chars>", "/reply reset"],
    status: "active",
    entrypointType: "weixin",
  },
  {
    action: "channel.send_file",
    groupId: "capabilities",
    summary: "将文件作为附件发送回当前聊天",
    terminal: ["channel send-file"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "channel:send-file",
    command: "channel",
    subcommand: "send-file",
    runner: "channel.send-file",
    argsSchemaKey: "channelSendFile",
    help: { topic: "channel", leafKey: "channel.send_file", detail: "leaf" },
  },
  {
    action: "timeline.event",
    groupId: "capabilities",
    summary: "按单个时间块写入时间轴，不必手写 JSON",
    terminal: ["timeline event"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:event",
    command: "timeline",
    subcommand: "event",
    runner: "timeline.event",
    argsSchemaKey: "timelineEvent",
    help: { topic: "timeline", leafKey: "timeline.event", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "timeline.write",
    groupId: "capabilities",
    summary: "按批量或原始 JSON 写入时间轴事件（低层入口）",
    terminal: ["timeline write"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:write",
    command: "timeline",
    subcommand: "write",
    runner: "timeline.subcommand",
    argsSchemaKey: "timelineWrite",
    help: { topic: "timeline", leafKey: "timeline.write", detail: "leaf" },
    timelineSubcommand: "write",
    approval: { autoApprove: true },
  },
  {
    action: "timeline.read",
    groupId: "capabilities",
    summary: "读取某一天的时间轴草稿或已发布内容",
    terminal: ["timeline read"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:read",
    command: "timeline",
    subcommand: "read",
    runner: "timeline.subcommand",
    argsSchemaKey: "timelineRead",
    help: { topic: "timeline", leafKey: "timeline.read", detail: "leaf" },
    timelineSubcommand: "read",
    approval: { autoApprove: true },
  },
  {
    action: "timeline.categories",
    groupId: "capabilities",
    summary: "查看可用分类、子类和 event node",
    terminal: ["timeline categories"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:categories",
    command: "timeline",
    subcommand: "categories",
    runner: "timeline.subcommand",
    argsSchemaKey: "timelineCategories",
    help: { topic: "timeline", leafKey: "timeline.categories", detail: "leaf" },
    timelineSubcommand: "categories",
    approval: { autoApprove: true },
  },
  {
    action: "timeline.proposals",
    groupId: "capabilities",
    summary: "根据自然语言生成候选时间轴事件",
    terminal: ["timeline proposals"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:proposals",
    command: "timeline",
    subcommand: "proposals",
    runner: "timeline.subcommand",
    argsSchemaKey: "timelineProposals",
    help: { topic: "timeline", leafKey: "timeline.proposals", detail: "leaf" },
    timelineSubcommand: "proposals",
    approval: { autoApprove: true },
  },
  {
    action: "timeline.build",
    groupId: "capabilities",
    summary: "构建时间轴静态页面",
    terminal: ["timeline build"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:build",
    command: "timeline",
    subcommand: "build",
    runner: "timeline.subcommand",
    argsSchemaKey: "timelineBuild",
    help: { topic: "timeline", leafKey: "timeline.build", detail: "leaf" },
    timelineSubcommand: "build",
    approval: { autoApprove: true },
  },
  {
    action: "timeline.serve",
    groupId: "capabilities",
    summary: "启动时间轴静态页面服务",
    terminal: ["timeline serve"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:serve",
    command: "timeline",
    subcommand: "serve",
    runner: "timeline.subcommand",
    argsSchemaKey: "timelineServe",
    help: { topic: "timeline", leafKey: "timeline.serve", detail: "leaf" },
    timelineSubcommand: "serve",
    approval: { autoApprove: true },
  },
  {
    action: "timeline.dev",
    groupId: "capabilities",
    summary: "启动时间轴热更新开发服务",
    terminal: ["timeline dev"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:dev",
    command: "timeline",
    subcommand: "dev",
    runner: "timeline.subcommand",
    argsSchemaKey: "timelineDev",
    help: { topic: "timeline", leafKey: "timeline.dev", detail: "leaf" },
    timelineSubcommand: "dev",
    approval: { autoApprove: true },
  },
  {
    action: "frame.build",
    groupId: "capabilities",
    summary: "构建平板常驻 Frame 页面",
    terminal: ["frame build"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "frame:build",
    command: "frame",
    subcommand: "build",
    runner: "frame.subcommand",
    argsSchemaKey: "frameBuild",
    help: { topic: "frame", leafKey: "frame.build", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "frame.serve",
    groupId: "capabilities",
    summary: "启动平板常驻 Frame 本地服务",
    terminal: ["frame serve"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "frame:serve",
    command: "frame",
    subcommand: "serve",
    runner: "frame.subcommand",
    argsSchemaKey: "frameServe",
    help: { topic: "frame", leafKey: "frame.serve", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "frame.dev",
    groupId: "capabilities",
    summary: "启动平板常驻 Frame 开发服务",
    terminal: ["frame dev"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "frame:dev",
    command: "frame",
    subcommand: "dev",
    runner: "frame.subcommand",
    argsSchemaKey: "frameDev",
    help: { topic: "frame", leafKey: "frame.dev", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "timeline.screenshot",
    groupId: "capabilities",
    summary: "截图时间轴页面",
    terminal: ["timeline screenshot"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "timeline:screenshot",
    command: "timeline",
    subcommand: "screenshot",
    runner: "timeline.screenshot",
    argsSchemaKey: "timelineScreenshot",
    help: { topic: "timeline", leafKey: "timeline.screenshot", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "reminder.create",
    groupId: "capabilities",
    summary: "创建提醒并交给调度层处理",
    terminal: ["reminder write"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "reminder:write",
    command: "reminder",
    subcommand: "write",
    runner: "reminder.write",
    argsSchemaKey: "reminderWrite",
    help: { topic: "reminder", leafKey: "reminder.create", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "diary.append",
    groupId: "capabilities",
    summary: "追加一条日记记录",
    terminal: ["diary write"],
    weixin: [],
    status: "active",
    entrypointType: "cli",
    scriptName: "diary:write",
    command: "diary",
    subcommand: "write",
    runner: "diary.write",
    argsSchemaKey: "diaryWrite",
    help: { topic: "diary", leafKey: "diary.append", detail: "leaf" },
    approval: { autoApprove: true },
  },
  {
    action: "app.help",
    groupId: "capabilities",
    summary: "查看当前通道可用命令",
    terminal: ["help"],
    weixin: ["/help"],
    status: "active",
    entrypointType: "cli",
    scriptName: "help",
    command: "help",
    runner: "help",
    argsSchemaKey: "appHelp",
    help: { topic: "", leafKey: "app.help", detail: "topic_only" },
  },
] as const satisfies readonly CommandActionDefinition[];
